from distutils.core import setup
setup(
  name = 'cppfunctions',
  packages = ['cppfunctions'],
  version = '2.1', 
  license='MIT',  
  description = 'My attempt to bring c/c++ functions to python',
  author = 'Shamyak',
  author_email = 'sj907822@gmail.com', 
  url = 'https://github.com/ShamyakGoel/cppfunctions/',
  download_url = 'https://github.com/ShamyakGoel/cppfunctions/archive/refs/tags/v_21.tar.gz',  
  keywords = ['c++functions', 'cfunctions'],
  install_requires=[],
  long_description_content_type="text/x-rst",
  classifiers=[
    'Development Status :: 3 - Alpha', 
    'Intended Audience :: Developers', 
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3',
  ],
)